# Generated by Django 3.1.5 on 2021-02-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0002_auto_20210202_1749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase_returns',
            new_name='PurchaseReturns',
        ),
    ]
