# Generated by Django 3.1.5 on 2021-02-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0003_auto_20210203_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturns',
            name='product_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_return', to='appshop.purchase'),
        ),
    ]
