# Generated by Django 3.1.5 on 2021-02-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0005_auto_20210205_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
